import prisma from "@/lib/prisma";

const articles = [
  {
    author: "Anand Krishnamoorthy",
    title: "Trump Tariff Threats Weigh on Asian Risk Appetite: Markets Wrap - Bloomberg.com",
    description: "European and US stock futures fell and haven assets… dollar weakened against most of its major peers.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://www.bloomberg.com/news/articles/2026-01-18-trump-tariff-threats-weigh-on-asian-risk-appetite-markets-wrap",
    urlToImage: null,
    sourceId: null,
    sourceName: "Bloomberg",
  },
  {
    author: "Cara Anna, Josh Boak",
    title: "$1 billion gets a permanent seat on Trump's Board …e for Gaza, as India and others invited - AP News",
    description: "At least eight more countries say the United States…cures permanent membership, while a three-year a…",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://apnews.com/article/gaza-israel-palestinian-board-peace-hamas-5f902ea2b1158f0a806c247d139ff62f",
    urlToImage: null,
    sourceId: null,
    sourceName: "AP News",
  },
  {
    author: "Javier Torres",
    title: "Wildfires race across Chile, leaving 18 dead and forcing thousands to flee - AP News",
    description: "Authorities in Chile say that wildfires raging across…mes. The South American country is sweltering un…",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://apnews.com/article/chile-wildfires-heat-biobio-emergency-c70c05758271270353606fa409fb504d",
    urlToImage: null,
    sourceId: null,
    sourceName: "AP News",
  },
  {
    author: "Michael David Smith",
    title: "Patriots favored by 4.5 at Broncos in AFC Championship Game - NBC Sports",
    description: "The Patriots will be road favorites in Denver in next weekend's AFC Championship Game.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://www.nbcsports.com/nfl/profootballtalk/rumors/patriots-favored-by-4-5-at-broncos-in-afc-championship-game",
    urlToImage: null,
    sourceId: null,
    sourceName: "NBC Sports",
  },
  {
    author: "Liam McKeone",
    title: "Texans’ C.J. Stroud Makes Unfortunate NFL History …Run of Turnovers in Playoffs - Sports Illustrated",
    description: "C.J. Stroud’s turnover numbers this postseason are unlike anything the NFL has ever seen.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://www.si.com/nfl/texans-cj-stroud-unfortunate-nfl-history-turnovers-in-playoffs",
    urlToImage: null,
    sourceId: null,
    sourceName: "Sports Illustrated",
  },
  {
    author: "Tom Henderson",
    title: "Footage of ZeniMax’s Cancelled Project Blackbird Surfaces Online - Insider Gaming",
    description: "Two minutes of in-engine footage of ZeniMax Online’s cancelled Project Blackbird has leaked online.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://insider-gaming.com/blackbrird-footage-leaked/",
    urlToImage: null,
    sourceId: null,
    sourceName: "Insider Gaming",
  },
  {
    author: "Madison Fernandez",
    title: "A Democratic governor’s blueprint for surviving Trump - Politico",
    description: "Phil Murphy, who leaves office Tuesday, has benefitted…on while avoiding the president’s public attacks.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://www.politico.com/news/2026/01/18/a-democratic-governors-blueprint-for-surviving-trump-00734703",
    urlToImage: null,
    sourceId: null,
    sourceName: "Politico",
  },
  {
    author: "Anne D'Innocenzio",
    title: "Trump's voice in a new Fannie Mae ad is generated …icial intelligence, with his permission - AP News",
    description: "What sounds like President Donald Trump narrating… push to make housing affordable and the president…",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://apnews.com/article/trump-voice-ai-housing-fannie-ad-davos-7a792aed20c56bcc3f7b53733ec331ad",
    urlToImage: null,
    sourceId: null,
    sourceName: "AP News",
  },
  {
    author: null,
    title: 'ReactOS For "Open-Source Windows" Achieves Massive Networking Performance Boost - Phoronix',
    description: "ReactOS as the long-in-development 'open-source Windows' project has been on quite a roll recently",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://www.phoronix.com/news/ReactOS-Async-Net-Connect",
    urlToImage: null,
    sourceId: null,
    sourceName: "Phoronix",
  },
  {
    author: "Ben Thompson",
    title: "Oregon man buys four 'refurbished' video game cons… up to see if they're legit - supercarblondie.com",
    description: "This Oregon man got his hands on four refurbished… at whether or not they were worth the investment",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://supercarblondie.com/are-refurbished-video-game-consoles-temu-legit/",
    urlToImage: null,
    sourceId: null,
    sourceName: "supercarblondie.com",
  },
  {
    author: null,
    title: "The Weekender: Outrageous Get-In Prices For The Na…candal Rocks College Basketball - Eleven Warriors",
    description: "National championship ticket prices reached record… point-shaving scandal rocked college basketball.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://www.elevenwarriors.com/college-sports/2026/ncaa-championship-trinidad-chambliss-sues-the-ncaa-and-a-point",
    urlToImage: null,
    sourceId: null,
    sourceName: "Eleven Warriors",
  },
  {
    author: "Kaia Hubbard",
    title: 'Minneapolis Mayor Jacob Frey says federal agents are an "occupying force" - CBS News',
    description: "Minneapolis Mayor Jacob Frey criticized the administration's federal agents as an occupying force.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://www.cbsnews.com/news/jacob-frey-minneapolis-mayor-face-the-nation-federal-agents/",
    urlToImage: null,
    sourceId: null,
    sourceName: "CBS News",
  },
  {
    author: "Faith Leroux",
    title: "5 Clever Uses For Your Old PlayStation 3 - bgr.com",
    description: "Even though the PlayStation 3 is going on 20 years old, you can give new life to the old console.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://www.bgr.com/2074854/uses-for-your-old-ps3/",
    urlToImage: null,
    sourceId: null,
    sourceName: "bgr.com",
  },
  {
    author: "Clarissa Brincat",
    title: "Why is flu season so bad this year? - Live Science",
    description: "Flu season in the U.S. is particularly bad this year, possibly due to a new branch of the flu family tree.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://www.livescience.com/health/flu/why-is-flu-season-so-bad-this-year",
    urlToImage: null,
    sourceId: null,
    sourceName: "Live Science",
  },
  {
    author: "Daniel Fienberg",
    title: "'The Fall and Rise of Reggie Dinkins' Review: Tracy Morgan NBC Comedy - The Hollywood Reporter",
    description: "Tina Fey and Robert Carlock (co-creator with Sam…) film star hoping a documentary will change his life.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "http://www.hollywoodreporter.com/tv/tv-reviews/the-fall-and-rise-of-reggie-dinkins-review-tracy-morgan-nbc-1236477044/",
    urlToImage: null,
    sourceId: null,
    sourceName: "The Hollywood Reporter",
  },
  {
    author: "Sarah Jones",
    title: "NASA Caught The Ocean Turning Strange Colors Around These Islands - The Daily Galaxy",
    description: "A glowing ring just appeared in the Pacific, and NASA caught it on camera.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://dailygalaxy.com/2026/01/nasa-ocean-strange-colors-around-islands/",
    urlToImage: null,
    sourceId: null,
    sourceName: "The Daily Galaxy",
  },
  {
    author: "Kelsey Tamborrino, Josh Siegel, Lesley Clark, Niina H. Farah",
    title: "Trump suffers major losses in his war on offshore wind - Politico",
    description: "The administration’s arguments that offshore wind …failed to convince judges in three separate courts.",
    content: "Full content here...",
    publishedAt: new Date("2026-01-18T00:00:00Z"),
    url: "https://www.politico.com/news/2026/01/18/trump-offshore-wind-problems-00734850",
    urlToImage: null,
    sourceId: null,
    sourceName: "Politico",
  },
];

async function main() {
  for (const article of articles) {
    await prisma.article.create({ data: article });
  }
  console.log("✅ Seed completed!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
